/* [BDP-MOCKS] Datos de prueba locales para visualizar las páginas BDP.
 * Se usan únicamente en modo demo; nunca se persisten ni se envían a BDP. */

import type { BdpArticleMap } from '@/api/generated/gestionRestauranteAPI.schemas';
import type { BdpPurchaseNote } from '@/api/bdp';
import type { BdpAuditEntry, BdpSnapshot } from '@/api/bdp-backup';

const hoy = new Date().toISOString();
const ayer = new Date(Date.now() - 86_400_000).toISOString();
const haceUnaSemana = new Date(Date.now() - 7 * 86_400_000).toISOString();

export const mockArticleMaps: BdpArticleMap[] = [
  {
    id: 'm1',
    user_id: 'u1',
    articulo_glory_codigo: 'ART-001',
    articulo_bdp_codigo: 'BDP-1001',
    articulo_bdp_nombre: 'Coca-Cola Zero 33cl',
    origen: 'bdp',
    local_dirty: false,
    descripcion: 'Refresco Coca-Cola Zero 33cl',
    precio_tarifa1: '2.50',
    iva_pct: '10',
    stock_actual: '120',
    activo: true,
    departamento: 1,
    familia: 10,
    subfamilia: 100,
    barcode: '8412345678901',
    ultima_sync_at: hoy,
    created_at: haceUnaSemana,
    updated_at: hoy,
  },
  {
    id: 'm2',
    user_id: 'u1',
    articulo_glory_codigo: 'ART-002',
    articulo_bdp_codigo: 'BDP-1002',
    articulo_bdp_nombre: 'Estrella Galicia 33cl',
    origen: 'bdp',
    local_dirty: false,
    descripcion: 'Cerveza Estrella Galicia 33cl',
    precio_tarifa1: '3.00',
    iva_pct: '21',
    stock_actual: '45',
    activo: true,
    departamento: 2,
    familia: 20,
    subfamilia: 200,
    barcode: '8412345678902',
    ultima_sync_at: hoy,
    created_at: haceUnaSemana,
    updated_at: hoy,
  },
  {
    id: 'm3',
    user_id: 'u1',
    articulo_glory_codigo: 'ART-003',
    articulo_bdp_codigo: 'BDP-1003',
    articulo_bdp_nombre: 'Jamón Ibérico 100g',
    origen: 'bdp',
    local_dirty: false,
    descripcion: 'Ración de jamón ibérico 100g',
    precio_tarifa1: '18.50',
    iva_pct: '10',
    stock_actual: '0',
    activo: true,
    departamento: 3,
    familia: 30,
    subfamilia: 300,
    barcode: '8412345678903',
    ultima_sync_at: ayer,
    created_at: haceUnaSemana,
    updated_at: ayer,
  },
  {
    id: 'm4',
    user_id: 'u1',
    articulo_glory_codigo: 'ART-004',
    articulo_bdp_codigo: 'BDP-1004',
    articulo_bdp_nombre: 'Tarta de queso',
    origen: 'bdp',
    local_dirty: false,
    descripcion: 'Tarta de queso casera',
    precio_tarifa1: '6.00',
    iva_pct: '10',
    stock_actual: '12',
    activo: false,
    departamento: 4,
    familia: 40,
    subfamilia: 400,
    barcode: '8412345678904',
    ultima_sync_at: haceUnaSemana,
    created_at: haceUnaSemana,
    updated_at: haceUnaSemana,
  },
  {
    id: 'm5',
    user_id: 'u1',
    articulo_glory_codigo: 'ART-005',
    articulo_bdp_codigo: 'BDP-1005',
    articulo_bdp_nombre: 'Café solo',
    origen: 'bdp',
    local_dirty: false,
    descripcion: 'Café solo',
    precio_tarifa1: '1.50',
    iva_pct: '10',
    stock_actual: '200',
    activo: true,
    departamento: 5,
    familia: 50,
    subfamilia: 500,
    barcode: '8412345678905',
    ultima_sync_at: hoy,
    created_at: haceUnaSemana,
    updated_at: hoy,
  },
  {
    id: 'm6',
    user_id: 'u1',
    articulo_glory_codigo: 'ART-006',
    articulo_bdp_codigo: 'BDP-1006',
    articulo_bdp_nombre: 'Botella agua 50cl',
    origen: 'bdp',
    local_dirty: false,
    descripcion: 'Botella de agua 50cl',
    precio_tarifa1: '1.20',
    iva_pct: '10',
    stock_actual: '0',
    activo: true,
    departamento: 1,
    familia: 11,
    subfamilia: 110,
    barcode: '8412345678906',
    ultima_sync_at: haceUnaSemana,
    created_at: haceUnaSemana,
    updated_at: haceUnaSemana,
  },
];

export interface BdpExplorerItem {
  id: number;
  type: 'menu' | 'fastfood' | 'pack';
  code: string;
  name: string;
  description: string;
  lines: { articleCode: string; articleName: string; quantity: number }[];
}

export const mockExplorerItems: BdpExplorerItem[] = [
  {
    id: 1,
    type: 'menu',
    code: 'MENU-01',
    name: 'Menú del día',
    description: 'Menú completo de lunes a viernes',
    lines: [
      { articleCode: 'ART-001', articleName: 'Coca-Cola Zero 33cl', quantity: 1 },
      { articleCode: 'ART-003', articleName: 'Jamón Ibérico 100g', quantity: 1 },
    ],
  },
  {
    id: 2,
    type: 'menu',
    code: 'MENU-02',
    name: 'Menú fin de semana',
    description: 'Menú especial fin de semana',
    lines: [
      { articleCode: 'ART-002', articleName: 'Estrella Galicia 33cl', quantity: 1 },
      { articleCode: 'ART-004', articleName: 'Tarta de queso', quantity: 1 },
    ],
  },
  {
    id: 3,
    type: 'pack',
    code: 'PACK-01',
    name: 'Pack familiar',
    description: 'Pack para 4 personas',
    lines: [
      { articleCode: 'ART-001', articleName: 'Coca-Cola Zero 33cl', quantity: 4 },
      { articleCode: 'ART-003', articleName: 'Jamón Ibérico 100g', quantity: 2 },
    ],
  },
  {
    id: 4,
    type: 'fastfood',
    code: 'FAST-01',
    name: 'Venta rápida barra',
    description: 'Modalidad de venta rápida en barra',
    lines: [
      { articleCode: 'ART-005', articleName: 'Café solo', quantity: 1 },
      { articleCode: 'ART-006', articleName: 'Botella agua 50cl', quantity: 1 },
    ],
  },
];

export const mockPurchaseNotes: BdpPurchaseNote[] = [
  {
    id: 'pn1',
    user_id: 'u1',
    serie: 'A',
    numero: '2024-0001',
    fecha: '2024-07-20',
    codigo_proveedor: 'PROV-001',
    nombre_proveedor: 'Bebidas del Norte',
    total: '250.00',
    estado: 'pendiente',
    gasto_id: null,
    datos_bdp: { DocumentNumber: '2024-0001', WarehouseCode: 'ALM-01' },
    ultima_sync_at: hoy,
    created_at: hoy,
    updated_at: hoy,
  },
  {
    id: 'pn2',
    user_id: 'u1',
    serie: 'A',
    numero: '2024-0002',
    fecha: '2024-07-21',
    codigo_proveedor: 'PROV-002',
    nombre_proveedor: 'Carnicería López',
    total: '420.50',
    estado: 'borrador',
    gasto_id: null,
    datos_bdp: { DocumentNumber: '2024-0002', WarehouseCode: 'ALM-01' },
    ultima_sync_at: ayer,
    created_at: ayer,
    updated_at: ayer,
  },
  {
    id: 'pn3',
    user_id: 'u1',
    serie: 'B',
    numero: '2024-0003',
    fecha: '2024-07-22',
    codigo_proveedor: 'PROV-003',
    nombre_proveedor: 'Pescados Mari',
    total: '180.25',
    estado: 'conciliado',
    gasto_id: 'g1',
    datos_bdp: { DocumentNumber: '2024-0003', WarehouseCode: 'ALM-02' },
    ultima_sync_at: hoy,
    created_at: hoy,
    updated_at: hoy,
  },
  {
    id: 'pn4',
    user_id: 'u1',
    serie: 'A',
    numero: '2024-0004',
    fecha: '2024-07-23',
    codigo_proveedor: 'PROV-001',
    nombre_proveedor: 'Bebidas del Norte',
    total: '95.00',
    estado: 'borrador',
    gasto_id: null,
    datos_bdp: { DocumentNumber: '2024-0004', WarehouseCode: 'ALM-01' },
    ultima_sync_at: hoy,
    created_at: hoy,
    updated_at: hoy,
  },
];

export const mockAuditEntries: BdpAuditEntry[] = [
  {
    id: 'a1',
    user_id: 'u1',
    operacion: 'create_order',
    direccion: 'glory_to_bdp',
    snapshot_pre_id: null,
    datos_enviados: { order_id: 'ORD-001', total: '45.00' },
    resultado: 'exito',
    datos_respuesta: { bdp_order_id: 12345 },
    error_mensaje: null,
    target_base_url: 'https://bdp.example.com',
    target_entity_type: 'order',
    target_entity_id: 'ORD-001',
    authorization_reason: 'Modo escritura temporal activado',
    created_at: hoy,
    updated_at: hoy,
  },
  {
    id: 'a2',
    user_id: 'u1',
    operacion: 'add_payment',
    direccion: 'glory_to_bdp',
    snapshot_pre_id: null,
    datos_enviados: { venta_id: 'V-002', amount: '20.00' },
    resultado: 'error',
    datos_respuesta: null,
    error_mensaje: 'Timeout al contactar con BDP',
    target_base_url: 'https://bdp.example.com',
    target_entity_type: 'payment',
    target_entity_id: 'V-002',
    authorization_reason: 'Pago parcial de comanda',
    created_at: ayer,
    updated_at: ayer,
  },
  {
    id: 'a3',
    user_id: 'u1',
    operacion: 'create_customer',
    direccion: 'glory_to_bdp',
    snapshot_pre_id: null,
    datos_enviados: { customer_name: 'Juan Pérez' },
    resultado: 'parcial',
    datos_respuesta: { bdp_customer_code: 99 },
    error_mensaje: null,
    target_base_url: 'https://bdp.example.com',
    target_entity_type: 'customer',
    target_entity_id: 'C-003',
    authorization_reason: 'Alta de nuevo cliente',
    created_at: haceUnaSemana,
    updated_at: haceUnaSemana,
  },
];

export const mockSnapshots: BdpSnapshot[] = [
  {
    id: 's1',
    user_id: 'u1',
    tipo: 'completo',
    direccion: 'bdp_to_glory',
    trigger_tipo: 'manual',
    datos: { articulos: 120, clientes: 45 },
    metadata: { export_profile: '1' },
    target_base_url: 'https://bdp.example.com',
    connection_fingerprint: 'fp-abc',
    created_at: hoy,
    expires_at: null,
    notas: 'Snapshot previo a sincronización de catálogo',
  },
  {
    id: 's2',
    user_id: 'u1',
    tipo: 'parcial',
    direccion: 'glory_to_bdp',
    trigger_tipo: 'manual',
    datos: { clientes: 5 },
    metadata: { tipo: 'clientes' },
    target_base_url: 'https://bdp.example.com',
    connection_fingerprint: 'fp-abc',
    created_at: ayer,
    expires_at: null,
    notas: 'Backup antes de importar clientes nuevos',
  },
];
